{% set version = "1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nsga2r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nsga2R_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nsga2R/nsga2R_{{ version }}.tar.gz
  sha256: 645111e633b5cd5b512e05ec9b943349c409fef6f8cf2ae81ae19958439b73ac

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mco
  run:
    - r-base
    - r-mco

test:
  commands:
    - $R -e "library('nsga2R')"           # [not win]
    - "\"%R%\" -e \"library('nsga2R')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nsga2R
  license: LGPL-3.0-only
  summary: This package provide functions for box-constrained multiobjective optimization using the elitist non-dominated sorting genetic algorithm - NSGA-II. Fast non-dominated sorting, crowding distance, tournament selection, simulated binary crossover, and polynomial mutation are called in the main program, nsga2R, to
    complete the search.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nsga2R
# Type: Package
# Title: Elitist Non-dominated Sorting Genetic Algorithm based on R
# Version: 1.0
# Date: 2013-06-12
# Author: Ching-Shih (Vince) Tsou <cstsou@mail.ntcb.edu.tw>
# Maintainer: Ming-Chang (Alan) Lee <alan9956@ydu.edu.tw>
# Description: This package provide functions for box-constrained multiobjective optimization using the elitist non-dominated sorting genetic algorithm - NSGA-II. Fast non-dominated sorting, crowding distance, tournament selection, simulated binary crossover, and polynomial mutation are called in the main program, nsga2R, to complete the search.
# Depends: mco
# License: LGPL-3
# Packaged: 2013-06-16 05:29:35 UTC; vince
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-06-16 18:26:19
